# Generated by Django 4.2.2 on 2023-06-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('cv', models.FileField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
