# Generated by Django 4.2.2 on 2023-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_form_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='cv',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='cv/'),
        ),
    ]
