# Generated by Django 4.2.2 on 2023-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_form_cv_alter_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='file/'),
        ),
    ]
