# Generated by Django 4.2.2 on 2023-06-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='cv',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/cv/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/file/'),
        ),
    ]
