# Generated by Django 4.2.2 on 2023-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_form_cv_alter_form_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='image/'),
        ),
    ]
